name: langchain_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain-core
    - langchain-community
    - langchain-ollama
    - langchain-openai
    - langchain-huggingface
    - langgraph
    - chromadb
    - rank-bm25
    - pypdf
    - sentence-transformers
    - pydantic
    - typing-extensions
    - openai
    - python-dotenv
    - pytest